// CLIENT CONFIGS
const DEFAULT_CLIENT_PORT = 5432;

const DEFAULT_CLIENT_CONFIG = {
  port: DEFAULT_CLIENT_PORT,
  origin: `http://localhost:${DEFAULT_CLIENT_PORT}`
};

// SERVER CONFIGS
const DEFAULT_SERVER_PORT = 4321;

const DEFAULT_SERVER_CONFIG = {
  port: DEFAULT_SERVER_PORT,
  origin: `http://localhost:${DEFAULT_SERVER_PORT}`
};

export { DEFAULT_CLIENT_CONFIG, DEFAULT_SERVER_CONFIG };
